# Generated by Django 5.0.6 on 2024-06-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='image',
            field=models.ImageField(default=1, upload_to='media/student_project_images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudentProjectImages',
        ),
    ]
