# Generated by Django 5.0.6 on 2024-06-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_studentproject_image_delete_studentprojectimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='people_image',
            field=models.FileField(default=1, upload_to='media/student_project_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='image',
            field=models.FileField(upload_to='media/student_project_images/'),
        ),
    ]
