# Generated by Django 5.0.6 on 2024-06-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='Course/Icon'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Course/Thumbnail'),
        ),
        migrations.AlterField(
            model_name='coursemoduleicons',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Course'),
        ),
    ]
