# Generated by Django 5.0.6 on 2024-06-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_icon_alter_course_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='Course/Icon'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='Course/Thumbnail'),
        ),
    ]
