# Generated by Django 5.0.6 on 2024-06-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='video',
            field=models.FileField(upload_to='student_feedback/video'),
        ),
    ]
