# Generated by Django 5.0.6 on 2024-06-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[(1, 'new'), (2, 'checked')], max_length=255),
        ),
    ]
