# Generated by Django 5.0.6 on 2024-06-05 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='mentor_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant', to='mentor.mentor'),
        ),
        migrations.DeleteModel(
            name='MentorAssistant',
        ),
    ]
